id: https://meaningfy.ws/schema/mssdks/mapping_suite_config
name: This schema defined the mapping suite configurations for extracting metadata from documents, and for eligibility checking mapping.
prefixes:
  linkml: https://w3id.org/linkml/
  cfg: https://meaningfy.ws/schema/mssdks/mapping_suite_config/
  skos: http://www.w3.org/2004/02/skos/core#
  dct: http://purl.org/dc/terms/
imports:
  - linkml:types
default_range: string
default_prefix: cfg

classes:
  MappingSuiteConfig:
    slots:
      - extractor_config
      - eligibility_constraint_config

  Extracor:
    slots:
      - field_key
      - field_extractors


  FieldExtractor:
    slots:
      - xpath
      - extraction_method
      - atribute_name

  EligibilityConstraint:
    slots:
      - xxx

slots:
  field_key:
  field_extractors:
    range: FieldExtractor
    multivalued: true
    inlined_as_list: true
  xpath:
    description: the XPath or XQuery expression to fetch values from the document
  extraction_method:
    range: ExtractionMethod
  attribute_name:
    description: the name of the attribute to be feteched from the `xpath` field
  eligibility_constraint_config:
    range: EligibilityConstraint
  extractor_config:
    range: Extracor

enums:
  ExtractionMethod:
    permissible_values:
      text:
      text_and_attribute: